sonar.projectKey=learnflow_frontend
sonar.projectName=learnflow Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.nuxt/**,**/coverage/**

sonar.organization=vzhyryk
sonar.host.url=https://sonarcloud.io