sonar.projectKey=learnflow_backend
sonar.projectName=learnflow Backend
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.

sonar.exclusions=**/*_test.go,**/vendor/**,**/tmp/**,**/dist/**,**/coverage.out
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=../tests/coverage.out

sonar.organization=vzhyryk
sonar.host.url=https://sonarcloud.io