name: Build & Test

permissions:
    contents: write

on:
    pull_request:
        branches: [main]

jobs:
    backend:
        name: backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.26.2"
                  cache-dependency-path: backend/go.sum

            - name: Vet
              working-directory: backend
              run: go vet ./...

            # - name: Lint
            #   working-directory: backend
            #   run: |
            #       go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            #       golangci-lint run

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                version: v2.12
                working-directory: backend

            - name: Test
              working-directory: backend
              run: go test ./... -race -count=1

            - name: Install Sonar
              run: npm install -g @sonar/scan

            - name: SonarQube Scan
              working-directory: backend
              run: sonar-scanner
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    frontend:
        name: frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: "22"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              working-directory: frontend
              run: npm install

            - name: Lint
              working-directory: frontend
              run: npm run lint

            - name: Type check
              working-directory: frontend
              run: npm run type-check

            - name: Install Sonar
              run: npm install -g @sonar/scan

            - name: SonarQube Scan
              working-directory: frontend
              run: sonar-scanner
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
